### ISSUE TITLE
DownloadTask 更新数据库中的下载信息

### ISSUE THREAD

**Issue by gaoneng102** [duzechao/DownloadManager#1]
DownloadTask 中，87行采取buffOffset 降低数据库操作次数的想法，我觉得很好。不过这里好像没代码并没加上，还是因为别的什么原因？

**Comment by duzechao** [comment]
感谢@gaoneng102  提醒，那代码是后来加上去的，忘记把下面的代码移上去了，更正代码如下：
if (buffOffset >= UPDATE_SIZE) {
                        // 更新数据库中的下载信息
                        buffOffset = 0;
                        dbEntity.setCompletedSize(completedSize);
                        downloadDao.update(dbEntity);
                        onDownloading();
                    }

**Comment by gaoneng102** [comment]
@duzechao onDownloading();这个监听放外面会不会好些。不然进度在buffOffset < UPDATE_SIZE怎么监听

**Comment by duzechao** [comment]
放里面的话可以保持和数据库数据的一致性，并且不会频繁调用监听，因为一般监听事件中都是更新UI的，这样可以减少UI的刷新频率。当然，也可以根据需要放在外面。thx
