### ISSUE TITLE
多个界面的监听怎么监听

### ISSUE THREAD

**Issue by i-show** [duzechao/DownloadManager#2]
当前添加监听的方法是 DownloadManager.addDownloadListener(task, DownloadTaskListener) 

在另外一个界面进行监听  task对象是没有的！

**Comment by duzechao** [comment]
已添加相应方法和简单实例，由于例子中文件太小，可换成较大的文件效果可能更明显，感谢您的宝贵意见！

**Comment by wlfcolin** [comment]
多个界面监听使用我这个吧，没有okhttp依赖，https://github.com/wlfcolin/file-downloader
有空我也整个基于okhttp的
