### ISSUE TITLE
更新进度的一点想法

### ISSUE THREAD

**Issue by xns1001** [duzechao/DownloadManager#5]
你现在的方案每次更新进度都要dao.update()，下载线程就会阻塞住,可读写数据库是很耗时的，感觉会影响下载速度。觉得再全局单独开一个线程来处理更新进度的数据库读写会好一点

**Comment by duzechao** [comment]
再开线程会造成两条线程不同步，写入的数据和数据库的数据不一致，可以在写入的时候不保存进数据库，只在线程结束的时候保存进度到数据库
